sudo: false

language: java

cache:
  directories:
    - $HOME/.m2
    - $HOME/spigot-build/history

before_install:
  - ./installSpigot.sh 1.13
  - ./installSpigot.sh 1.12.2
  - ./installSpigot.sh 1.11.2

install:
  - mvn clean compile
  - ant instrument
  - travis_retry mvn test
  - ant report

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF unittests
